@Base_URL = https://repoexplorer-h4t7.onrender.com/api


### Get User
GET {{Base_URL}}/user/torvalds

### Get Repos - Page 1, Sort by Updated
GET http://localhost:3000/api/user/torvalds/repos?page=1&sort=updated

### Get Repos - Page 2, Sort by Updated
GET http://localhost:3000/api/user/torvalds/repos?page=2&sort=updated

### Get Repos - Sort by Name
GET http://localhost:3000/api/user/torvalds/repos?page=1&sort=name

### Get Repos - Sort by Stars
GET http://localhost:3000/api/user/torvalds/repos?page=1&sort=stars

### Get Languages
GET http://localhost:3000/api/user/torvalds/languages

### Get Repos Sorted by Stars (all repos)
GET http://localhost:3000/api/user/torvalds/repos/stars